import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import { Table } from '@mantine/core'

import DocumentDisplay from '../components/DocumentDisplay'
import getMockData, { User } from '../lib/mock'
import styles from '../styles/Home.module.scss'

const Home: NextPage<{ users: User[] }> = ({ users }) => {
  const rows = users.map((user) => (
    <tr key={`${user.firstName} ${user.lastName}`}>
      <td>{ user.firstName }</td>
      <td>{ user.lastName }</td>
      <td>{ user.country }</td>
      <td>
        <DocumentDisplay
          documents={user.documents}
        />
      </td>
    </tr>
  ))

  return (
    <div>
      <Head>
        <title>Code Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Table striped className={styles.table}>
          <colgroup>
            <col style={{ width: '20%' }} />
            <col style={{ width: '20%' }} />
            <col style={{ width: '20%' }} />
            <col style={{ width: '40%' }} />
          </colgroup>
          <thead>
            <tr>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Country</th>
              <th>Documents</th>
            </tr>
          </thead>
          <tbody>
            { rows }
          </tbody>
        </Table>
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      users: getMockData(),
    }
  }
}

export default Home
